package com.hud.briefing;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import java.time.LocalDate;
import java.util.List;

public interface DailyBriefingRepository extends JpaRepository<DailyBriefing, Long> {
    
    @Query("SELECT b FROM DailyBriefing b WHERE CAST(b.generatedAt AS date) = CURRENT_DATE")
    List<DailyBriefing> findLatestToday();

    @Query("SELECT b FROM DailyBriefing b WHERE CAST(b.generatedAt AS date) = CURRENT_DATE AND b.modelName = :modelName")
    List<DailyBriefing> findByModelToday(String modelName);

    /**
     * Finds the most recent briefing for each category.
     */
    @Query("SELECT b FROM DailyBriefing b WHERE b.generatedAt = (SELECT MAX(b2.generatedAt) FROM DailyBriefing b2 WHERE b2.category = b.category)")
    List<DailyBriefing> findLatestGlobal();

    /**
     * Finds the most recent briefing for each category generated by a specific model.
     */
    @Query("SELECT b FROM DailyBriefing b WHERE b.modelName = :modelName AND b.generatedAt = (SELECT MAX(b2.generatedAt) FROM DailyBriefing b2 WHERE b2.category = b.category AND b2.modelName = :modelName)")
    List<DailyBriefing> findByModelLatest(String modelName);

    void deleteByCategoryAndModelNameAndGeneratedAtAfter(BriefingCategory category, String modelName, java.time.LocalDateTime after);
    long countByGeneratedAtAfter(java.time.LocalDateTime after);
}
